name: Terraform Plan

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan

      - name: Show Plan Output
        run: terraform show -no-color tfplan > plan.txt

      - name: Upload plan output
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: |
            tfplan
            plan.txt
