name: Terraform Destroy

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

jobs:
  destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
