name: Terraform Plan

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout full repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Terraform Init
        run: terraform -chdir=${{ inputs.working-directory }} init -input=false -reconfigure

      - name: Terraform Plan
        run: terraform -chdir=${{ inputs.working-directory }} plan -input=false -var-file=${{ inputs.working-directory }}/terraform.tfvars -out=tfplan
