name: Terraform Destroy Reusable Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

      component:
        required: true
        type: string

      aws_region:
        required: true
        type: string

      role_to_assume:
        required: true
        type: string

      tfvars_file:
        required: true
        type: string

      confirm_destroy:
        required: true
        type: string
    secrets:
      SYS_PUBKEY:
        required: true

jobs:
  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    environment:
      name: production

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: environments/${{ inputs.environment }}/${{ inputs.component }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Confirmation
        working-directory: .
        run: |
          if [ "${{ inputs.confirm_destroy }}" != "DESTROY" ]; then
            echo "Confirmation failed"
            exit 1
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role_to_assume }}
          aws-region: ${{ inputs.aws_region }}

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Destroy
        run: |
          terraform destroy \
            -auto-approve \
            -input=false \
            -var-file="${{ inputs.tfvars_file }}"
        env:
          TF_VAR_public_key: ${{ secrets.SYS_PUBKEY }}