name: Terraform Validate

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Terraform Validate
        run: terraform validate
